# [ SchoolManagementSystem]

In [0]:
USE [master]
GO

In [0]:
/****** Object:  Database [ SchoolManagementSystem]    Script Date: 11/03/2024 21:26:49 ******/
CREATE DATABASE [ SchoolManagementSystem]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N' SchoolManagementSystem', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\ SchoolManagementSystem.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N' SchoolManagementSystem_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\ SchoolManagementSystem_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [ SchoolManagementSystem] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ SchoolManagementSystem].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [ SchoolManagementSystem] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [ SchoolManagementSystem] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [ SchoolManagementSystem] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [ SchoolManagementSystem] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [ SchoolManagementSystem] SET ARITHABORT OFF 
GO
ALTER DATABASE [ SchoolManagementSystem] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [ SchoolManagementSystem] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [ SchoolManagementSystem] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [ SchoolManagementSystem] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [ SchoolManagementSystem] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [ SchoolManagementSystem] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [ SchoolManagementSystem] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [ SchoolManagementSystem] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [ SchoolManagementSystem] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [ SchoolManagementSystem] SET  DISABLE_BROKER 
GO
ALTER DATABASE [ SchoolManagementSystem] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [ SchoolManagementSystem] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [ SchoolManagementSystem] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [ SchoolManagementSystem] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [ SchoolManagementSystem] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [ SchoolManagementSystem] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [ SchoolManagementSystem] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [ SchoolManagementSystem] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [ SchoolManagementSystem] SET  MULTI_USER 
GO
ALTER DATABASE [ SchoolManagementSystem] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [ SchoolManagementSystem] SET DB_CHAINING OFF 
GO
ALTER DATABASE [ SchoolManagementSystem] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [ SchoolManagementSystem] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [ SchoolManagementSystem] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [ SchoolManagementSystem] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [ SchoolManagementSystem] SET QUERY_STORE = ON
GO
ALTER DATABASE [ SchoolManagementSystem] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

# [dbo].[Courses]

In [0]:
USE [ SchoolManagementSystem]
GO

In [0]:
/****** Object:  Table [dbo].[Courses]    Script Date: 11/03/2024 21:26:50 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Courses](
	[CourseID] [int] IDENTITY(101,1) NOT NULL,
	[CourseName] [nvarchar](100) NULL,
PRIMARY KEY CLUSTERED 
(
	[CourseID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[Enrolments]

In [0]:
/****** Object:  Table [dbo].[Enrolments]    Script Date: 11/03/2024 21:26:50 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Enrolments](
	[EnrollmentID] [int] IDENTITY(1,1) NOT NULL,
	[StudentID] [int] NULL,
	[CourseID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[EnrollmentID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[Students]

In [0]:
/****** Object:  Table [dbo].[Students]    Script Date: 11/03/2024 21:26:50 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Students](
	[StudentID] [int] IDENTITY(1,1) NOT NULL,
	[FirstName] [nvarchar](50) NULL,
	[LastName] [nvarchar](50) NULL,
	[GradeLevel] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[StudentID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [FK__Enrolment__Cours__3C69FB99]

In [0]:
ALTER TABLE [dbo].[Enrolments]  WITH CHECK ADD FOREIGN KEY([CourseID])
REFERENCES [dbo].[Courses] ([CourseID])
GO

# [FK__Enrolment__Stude__3B75D760]

In [0]:
ALTER TABLE [dbo].[Enrolments]  WITH CHECK ADD FOREIGN KEY([StudentID])
REFERENCES [dbo].[Students] ([StudentID])
GO

# [ SchoolManagementSystem]

In [0]:
USE [master]
GO

In [0]:
ALTER DATABASE [ SchoolManagementSystem] SET  READ_WRITE 
GO